apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc-foursix
  name: api-loadbalancer-svc-foursix
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5293
  selector:
    app: api-pod-foursix
  type: LoadBalancer
