apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: foursixsql
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqlserver-pod
  type: LoadBalancer
