name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x
    - name: test
      run: dotnet test --no-build --verbosity normal
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Docker Image
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t $DOCKER_USERNAME/foursix:latest .
        docker push $DOCKER_USERNAME/foursix:latest
      env : 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


        
  
